apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: bundle/config/upstream
    contents:
      - path: .
        githubRelease:
          slug: vmware-tanzu/cluster-api-provider-byoh
          tag: v0.3.0
          disableAutoChecksumValidation: true
        includePaths:
          - infrastructure-components.yaml
          - metadata.yaml
